// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPTJfhY5t6pET-nH3TzKNhgN4LofUInVk',
    appId: '1:798114358033:web:cdce0ef27269183fd6a2b0',
    messagingSenderId: '798114358033',
    projectId: 'signin-example-19435',
    authDomain: 'signin-example-19435.firebaseapp.com',
    storageBucket: 'signin-example-19435.appspot.com',
    measurementId: 'G-JL51FKR8J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYFkr_cysmoc4HkTVxaKRs5fiOcRyfuEc',
    appId: '1:798114358033:android:d8132bd5a0bec17bd6a2b0',
    messagingSenderId: '798114358033',
    projectId: 'signin-example-19435',
    storageBucket: 'signin-example-19435.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP00uFJiqprakD-arlyHD4eptWSfe17Ps',
    appId: '1:798114358033:ios:8c717526a2ccb4cad6a2b0',
    messagingSenderId: '798114358033',
    projectId: 'signin-example-19435',
    storageBucket: 'signin-example-19435.appspot.com',
    iosBundleId: 'com.example.flutterApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP00uFJiqprakD-arlyHD4eptWSfe17Ps',
    appId: '1:798114358033:ios:8c717526a2ccb4cad6a2b0',
    messagingSenderId: '798114358033',
    projectId: 'signin-example-19435',
    storageBucket: 'signin-example-19435.appspot.com',
    iosBundleId: 'com.example.flutterApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPTJfhY5t6pET-nH3TzKNhgN4LofUInVk',
    appId: '1:798114358033:web:12be0c2b810fe996d6a2b0',
    messagingSenderId: '798114358033',
    projectId: 'signin-example-19435',
    authDomain: 'signin-example-19435.firebaseapp.com',
    storageBucket: 'signin-example-19435.appspot.com',
    measurementId: 'G-2BXSBCZD22',
  );
}
